### ISSUE TITLE
Skill credit - Registering credit no matter the skill

### ISSUE THREAD

**Issue by Rismr1** [Browsit/mcMMOQuestsModule#4]
So I have created a bunch of quests with the module and when I setup a quest with the level up skill objective, I select a specific skill to level up in.  But when the player is doing the quest for example I have a Archery quest with the objective of leveling 3 levels in archery, they can level up any skill and they will receive credit no matter what skill they leveled up even when I specify in the quest editor to only accept levels in archery.

Here is a quest example

```yaml
  custom115:
    name: Levels - Archery
    ask-message: 'Gain 3 Levels in Archery. Then report to Officer Jenny. Rewards:
      $750 1QP 200XP ITEM: Gold Ingot x3'
    finish-message: Quest Completed!
    npc-giver-uuid: f0f4fcef-6f81-4608-9e79-89537d8d2a0f
    gui-display:
      ==: org.bukkit.inventory.ItemStack
      v: 3337
      type: BOW
    stages:
      ordered:
        '1':
          custom-objectives:
            custom1:
              name: mcMMO Overhaul Level Up Objective
              count: 3
              data:
                MMO Level Obj: Level up skill
                MMO Level Types: Archery
          start-message: '&bGain &63 &2Levels &bin &6Archery&b.'
          complete-message: Quest Objective Completed!
        '2':
          npc-uuids-to-talk-to:
          - f0f4fcef-6f81-4608-9e79-89537d8d2a0f
          start-message: '&bReport to &aOfficer Jenny &bin the &cWindria Barracks
            &bnext to &cWindria Castle&b.'
          complete-message: Quest Objective Completed!
    rewards:
      items:
      - ==: org.bukkit.inventory.ItemStack
        v: 3337
        type: GOLD_INGOT
        amount: 3
      money: 750
      quest-points: 1
      exp: 200
    planner:
      cooldown: 86400
```
